# Generated by Django 5.0 on 2024-04-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_is_user',
            field=models.BooleanField(default=False),
        ),
    ]
