# Generated by Django 5.0 on 2024-04-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_sender_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.ManyToManyField(to='app.message'),
        ),
    ]
