# Generated by Django 5.0 on 2024-04-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_is_user',
        ),
    ]
